
theme = "gruvbox_dark_hard"

[keys.normal]
"C-s" = [":w"]
"C-r" = [":config-reload"]
"=" = [ ":format" ]
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["move_line_down", "goto_first_nonwhitespace"] # Maps the enter key to move to start of next line
X = "extend_line_above"
D = "delete_char_backward"
esc = ["collapse_selection", "keep_primary_selection"]

[editor]
true-color = true
bufferline = "multiple"
mouse = false


[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true


[keys.normal.'\']
'd' = ["extend_line_below",''':pipe-to tmux load-buffer - \; paste-buffer -dpr -t '{right-of}' \; send-keys -t '{right-of}' Enter''', "collapse_selection", "move_visual_line_down"]
'p' = [''':pipe-to tmux load-buffer - \; "paste-buffer" -dpr -t '{right-of}' \; send-keys -t '{right-of}' Enter''']
's' = [''':pipe-to tmux load-buffer - \; save-buffer buffer.txt \; send-keys -t '{right-of}' Enter; sh /home/vojtam/.config/helix/R_repl/str_r.sh''']
space = [''':pipe-to tmux load-buffer - \; paste-buffer -dpr -t '{right-of}' \; send-keys -t '{right-of}' Enter''']
'\' = [''':sh tmux send-keys Q/# Space %% Enter O# Escape Escape Nvg.a BSpace BSpace Escape Escape \\ Space uuQ''']
# the above is the quivalent of putting, in .tmux.conf: send-keys Q/#\s%%\rO#\e\eNvg.a\b\b\e\e\\\suuQ


